apiVersion: v1
kind: Service
metadata:
  name: optillm-service
  namespace: default
  labels:
    app: optillm-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: optillm-gateway
